services:
  # Full-Stack Service (Server + Frontend Static Build + JSON database)
  - type: web
    name: smarttodo-app
    env: node
    plan: free
    buildCommand: npm install && npm run build:client
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 5000
      - key: DB_PORT
        value: 3001
      - key: DB_URL
        value: http://localhost:3001
      - key: VITE_API_URL
        value: http://localhost:5000/api
